provider "azurerm" {
  features {}
}

provider "azuread" {
}

locals {
  infra_rg_name       = "aks-poc"
  infra_nodes_rg_name = "aks-poc-nodes"
}

# The main resource group
resource "azurerm_resource_group" "main" {
  name     = local.infra_rg_name
  location = var.location
}

# The AKS nodes resource group (auto generated by AKS cluster)
data "azurerm_resource_group" "nodes" {
  name = local.infra_nodes_rg_name
  # location   = var.location # Add the location attribute here
  depends_on = [azurerm_kubernetes_cluster.main]
}

# Setting up networking
# use an existing VNET
resource "azurerm_virtual_network" "main" {
  name                = "aks-poc-vnet"
  address_space       = ["10.0.0.0/16"]
  resource_group_name = azurerm_resource_group.main.name
  location            = var.location
}

# create the subnet
resource "azurerm_subnet" "aks" {
  name                 = "aks-subnet"
  address_prefixes     = ["10.0.1.0/24"]
  virtual_network_name = azurerm_virtual_network.main.name
  resource_group_name  = azurerm_resource_group.main.name
}

# secure it
resource "azurerm_network_security_group" "aks" {
  location            = var.location                     # Add the location attribute here
  name                = "my-nsg"                         # Add the name attribute here
  resource_group_name = azurerm_resource_group.main.name # Add the resource_group_name attribute here

  security_rule {
    # Add security rule attributes here
    name                       = "allow_ssh"
    priority                   = 1001
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "22"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }
}

# create a public IP for the LB
resource "azurerm_public_ip" "public_lb" {
  name                = "aks-poc-lb"
  resource_group_name = local.infra_nodes_rg_name
  location            = var.location # Add the location attribute here
  allocation_method   = "Static"     # Add the allocation_method attribute here with a valid value
  depends_on          = [azurerm_kubernetes_cluster.main]
}

# AKS cluster
resource "azurerm_kubernetes_cluster" "main" {
  name                = var.kubernetes_cluster_name
  location            = var.location
  resource_group_name = azurerm_resource_group.main.name
  dns_prefix          = var.kubernetes_cluster_name
  node_resource_group = local.infra_nodes_rg_name
  kubernetes_version  = "1.28"

  default_node_pool {
    name                        = "default"
    node_count                  = 2
    os_disk_size_gb             = 30
    vm_size                     = "Standard_D2_v2"
    temporary_name_for_rotation = "tmpdefault"
    # vnet_subnet_id              = azurerm_subnet.aks.id
  }

  linux_profile {
    admin_username = "azureuser"
    ssh_key {
      key_data = file("~/.ssh/id_rsa_azure.pub")
    }
  }

  identity {
    type = "SystemAssigned"
  }

  azure_active_directory_role_based_access_control {
    managed            = true
    azure_rbac_enabled = true
    # admin_group_object_ids = var.kubernetes_rbac_admin_groups
  }
}