---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-v2-secure
  annotations:
    external-dns.alpha.kubernetes.io/hostname: labs.molntek.com
spec:
  ports:
    - port: 8080
      protocol: TCP
  type: ClusterIP
  selector:
    app: echoserver-v2-secure
